config/routes.rb
Mtm::Application.routes.draw do
  devise_for :users

  resources :categories

  resources :areas

  resources :brands

  resources :products do
    resources :matches
  end

  root :to => 'pages#home'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :brand
  belongs_to :product
  attr_accessible :color, :description, :link, :luminosity, :name, :overall, :price, :texture, :brand_id, :photo

  has_attached_file :photo, styles: {
  	thumb: '50x50#',
  	square: '250x250#'
  }, :default_url => "/assets/missing.png"
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_product

  def find_product
    @product = Product.find(params[:product_id])
  end

  # GET /matches
  # GET /matches.json
  def index
    @matches = @product.matches

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new
    @brands = Brand.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
    @brands = Brand.all
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = @product.matches.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to product_matches_path(@product), notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to product_matches_path(@product), notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to product_matches_path(@product) }
      format.json { head :no_content }
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for [@product, @match] do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field five_twelfths left">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field one_sixth left">
    <%= f.label :price %><br />
    <%= f.number_field :price, :min => 0, :step => 0.01  %>
  </div>
  <div class="field five_twelfths left last_column">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="clearfix"></div>
  <div class="field row">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="clearfix"></div><br>
  <div class="field one_half left">
    <%= f.label :brand_id %><br />
    <%= collection_select(:match, :brand_id, @brands, :id, :name, { :include_blank => true }) %>
  </div>
  <div class="field one_fourth left">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="clearfix"></div>
<br />
<legend><h2>Match Ratings</h2></legend>

  <div class="field one_sixth left">
    <%= f.label :color %><br />
    <%= f.number_field :color, :min => 0, :max => 5, :step => 0.5 %>
  </div>
  <div class="field one_sixth left">
    <%= f.label :texture %><br />
    <%= f.number_field :texture, :min => 0, :max => 5, :step => 0.5  %>
  </div>
  <div class="field one_sixth left">
    <%= f.label :luminosity %><br />
    <%= f.number_field :luminosity, :min => 0, :max => 5, :step => 0.5  %>
  </div>
  <div class="field shift_one one_fourth left">
    <%= f.label :overall %><br />
    <%= f.number_field :overall, :min => 0, :max => 100, :step => 0.01  %>
  </div>
  <div class="clearfix"></div><br>
  <div class="actions text-center">
    <%= f.submit 'Submit', class: "btn btn-inverse btn-large" %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<div class="container">
	<div class="page-header">
		<h1>Edit match</h1>
	</div>
	<%= render 'form' %>
</div>

app/views/matches/index.html.erb
<div class="container">
    <div class="page-header">
        <h1>Matches</h1>

    </div>

    <div class="left three_fourths text-left"><h3 class="" style="margin:10px 0;"><strong><%= @product.brand.name %></strong> <%= @product.name %></h3></div>
    <%= link_to 'NEW MATCH', new_product_match_path(@product), :class => "btn btn-success btn-small right" %>
    <!--<div class="row product">
        <div class="one_twelfth"><%= image_tag @product.photo(:square) %></div>
        <div class="three_fourths"><h3><strong><%= @product.brand.name %></strong> <%= @product.name %></h3></div>
        <%= link_to 'NEW MATCH', new_product_match_path(@product), :class => "btn btn-success btn-small right" %>
    </div>-->



<% if @matches.count == 0 %>
    <div class="row product"><h4>No matches</h4></div>
<% else %>
  <div class="row product header">
    <div class="one_twelfth">Photo</div>
    <div class="five_twelfths">Details</div>
    <div class="one_twelfth">Color</div>
    <div class="one_twelfth">Texture</div>
    <div class="one_twelfth">Lumin.</div>
    <div class="one_twelfth">Overall</div>
    <div class="one_sixth last_column">Price</div>
  </div>

  <% @matches.each do |match| %>
  <div class="row product solid-white">
    <div class="one_twelfth">
        <%= image_tag match.photo(:square) %>
    </div>
    <div class="five_twelfths">
        <strong><%= match.brand.name %></strong> <%= match.name %>
        <p><%= match.description %></p>
    </div>
    <div class="one_twelfth"><h4><%= match.color %></h4></div>
    <div class="one_twelfth"><h4><%= match.texture %></div>
    <div class="one_twelfth"><h4><%= match.luminosity %></div>
    <div class="one_twelfth"><h4><%= number_to_percentage(match.overall, :precision => 0) %></div>
    <div class="one_sixth">
        <div class="left"><h4><%= number_to_currency(match.price) %></div>
        <div class="text-right">
            <%= link_to 'Edit', edit_product_match_path(match.product, match), :class => 'btn btn-warning' %><br />
            <%= link_to 'Del', product_match_path(match.product, match), method: :delete, data: { confirm: 'Are you sure you want to delete this match?' }, :class => 'btn btn-danger' %>
        </div>
    </div>
  </div>
  <% end %>
<% end %>
</div>

app/views/matches/new.html.erb
<div class="container">
	<div class="page-header">
		<h1>Add a new match</h1>
	</div>
	<%= render 'form' %>
</div>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @match.name %>
</p>

<p>
  <b>Price:</b>
  <%= @match.price %>
</p>

<p>
  <b>Link:</b>
  <%= @match.link %>
</p>

<p>
  <b>Description:</b>
  <%= @match.description %>
</p>

<p>
  <b>Brand:</b>
  <%= @match.brand %>
</p>

<p>
  <b>Product:</b>
  <%= @match.product %>
</p>

<p>
  <b>Color:</b>
  <%= @match.color %>
</p>

<p>
  <b>Texture:</b>
  <%= @match.texture %>
</p>

<p>
  <b>Luminosity:</b>
  <%= @match.luminosity %>
</p>

<p>
  <b>Overall:</b>
  <%= @match.overall %>
</p>


<%= link_to 'Edit', edit_product_match_path(@match.product, @match) %>