config/routes.rb
Mtm::Application.routes.draw do
  devise_for :users

  resources :categories

  resources :areas

  resources :brands

  resources :products do
    resources :matches
  end

  root :to => 'pages#home'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  belongs_to :area
  belongs_to :category
  has_many :matches
  attr_accessible :description, :link, :name, :price, :brand_id, :area_id, :category_id, :photo

  has_attached_file :photo, styles: {
    square: '250x250#'
  }, :default_url => "/assets/missing.png"

  include PgSearch
  pg_search_scope :search, against: [:name, :description],
  	using: {tsearch: {dictionary: "english"}},
  	associated_against: {brand: :name, area: :name, category: :name}

  def self.seek(query)
  	search(query)
  	# scoped
  end

  def self.similar(query)
		results = search(query)
		ids = []
    areas = []
		results.each do |result|
			ids.push(result.id)
      areas.push(result.area_id)
		end
		Product.find(:all, :conditions => ['id NOT IN (?) AND area_id IN (?)', ids, areas])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if(!params[:q] || params[:q] == "")
      if(user_signed_in? && current_user.is_admin?)
        @products = Product.find(:all, :order => "updated_at DESC")
        render template: 'products/matrix'
      else
        redirect_to root_url
      end
    else
      @products = Product.search(params[:q])
      @similar = Product.similar(params[:q])

      respond_to do |format|
        format.html { render layout: "clean" } # index.html.erb
        format.json { render json: @products }
      end
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html { redirect_to products_path({:q => @product.name}), :notice => flash[:notice] }
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @brands = Brand.all
    @areas = Area.all
    @categories = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
    @brands = Brand.all
    @areas = Area.all
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for (@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field five_twelfths left">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field one_sixth left">
    <%= f.label :price %><br />
    <%= f.text_field :price, :min => 0, :step => 0.01 %>
  </div>
    <div class="field five_twelfths left last_column">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="clearfix"></div><br>
  <div class="field left row">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="clearfix"></div><br>
  <div class="field one_fourth">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>
  <div class="field one_fourth">
    <%= f.label :area_id %><br />
    <%= collection_select(:product, :area_id, @areas, :id, :name, { :include_blank => true }) %>
  </div>
  <div class="field one_fourth">
    <%= f.label :category_id %><br />
    <%= collection_select(:product, :category_id, @categories, :id, :name, { :include_blank => true }) %>
  </div>
  <div class="field one_fourth last_column">
    <%= f.label :brand_id %><br />
    <%= collection_select(:product, :brand_id, @brands, :id, :name, { :include_blank => true }) %>
  </div>
  <div class="clearfix"></div><br>
<br>
  <div class="actions text-center">
    <%= f.submit 'Submit', class: "btn btn-inverse btn-large" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<li data-id="<%= product.id %>" data-name="<%= product.name %>" data-price="<%= number_to_currency(product.price) %>" data-link="<%= product.link %>" data-description="<%= product.description %>" data-photo="<%= product.photo.url(:square) %>" <% if !product.brand.nil? %>data-brand="<%= product.brand.name %>"<% end %> <% if !product.area.nil? %>data-area="<%= product.area.name %>"<% end %> <% if !product.category.nil? %>data-category="<%= product.category.name %>"<% end %>>
    <%= image_tag product.photo.url(:square) %>
    <p><span class="brand"><%= product.brand.name %></span></p>
    <p><%= truncate(product.name, :length => 35) %></p>
    <% product.matches.each do |match| %>
    	<span class="match" data-id="<%= match.id %>" data-brand="<%= match.brand.name %>" data-name="<%= match.name %>" data-link="<%= match.link %>" data-color="<%= match.color %>" data-luminosity="<%= match.luminosity %>" data-texture="<%= match.texture %>" data-overall="<%= number_to_percentage(match.overall, :precision => 0) %>" data-photo="<%= match.photo.url(:square) %>" data-price="<%= number_to_currency(match.price, :precision => 0) %>" data-description="<%= match.description %>"></span>
    <% end %>
</li>

app/views/products/edit.html.erb
<div class="container">
	<div class="page-header">
		<h1>Editing product</h1>
	</div>
	<%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class="search">
    <div id="logo" class="left">
        <%= link_to image_tag('header-logo.png', :size => '305x30'), root_path %>
    </div>
    <%= form_tag products_path, :method => 'get' do %>
        <div class="left searchbox">
            <%= text_field_tag :q, params[:q] %>
        </div>
        <%= submit_tag "Go", :name => nil, class: "btn btn-inverse btn-small" %>
        <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-danger btn-small right' %>
        <% end %>
    <% end %>
</div>

<div class="master">
    <ul class="products">
        <%= render :partial => 'product', :collection => @products %>
        <% if user_signed_in? && current_user.is_admin %>
        <li data-name="New Product">
            <img src="http://placehold.it/250x250/ffffff/000000&text=Add" alt="Add" />
            <p><span class="brand"><%= link_to 'New Product', new_product_path %></span></p>
            <p>its quite good</p>
        </li>
        <% end %>
    </ul>
    <h3>Similar</h3>
    <ul class="products">
        <%= render :partial => 'product', :collection => @similar %>
    </ul>
</div>

<div class="detail">

</div>

<script id="product-template" type="text/x-handlebars-template">
    <div class="product-image left">
        <img src="{{photo}}" class="left">
    </div>
    <div class="description left">
        <h3><span class="brand">{{brand}}</span></h3>
        <h4>{{name}}</h4>
        <p>
            {{description}}<br /><br />
            <div class="left one_half">
            <h5>{{price}}</h5>
            </div>
            <div class="left one_fourth">
            <a href="{{link}}" class="btn btn-danger">Buy</a>
            </div>
            <div class="clearfix"></div>
            <% if user_signed_in? && current_user.is_admin %>
            <a href="/products/{{id}}/matches/new" class="btn btn-primary">Add Match</a>
            <a href="/products/{{id}}/edit" class="btn btn-warning">Edit</a>
            <% end %>
        </p>
    </div>


    <h3 id="matched-products">Matched Products</h3>
    <ul class="matches">
        {{#each matches}}
        <li class="match left" data-id="{{id}}" data-name="{{name}}" data-price="{{price}}" data-link="{{link}}" data-description="{{description}}" data-photo="{{photo}}" data-brand="{{brand}}">
            <div><img src="{{photo}}"></div>
            <div class="name">
                <h3>{{brand}}</h3>
                <h4>{{name}}</h4>
            </div>
            <div>
                <h5>Color</h5>
                <div class="stars">
                    {{stars color}}
                </div>
            </div>
            <div>
                <h5>Texture</h5>
                <div class="stars">
                    {{stars texture}}
                </div>
            </div>
            <div>
                <h5>Luminosity</h5>
                <div class="stars">
                    {{stars luminosity}}
                </div>
            </div>
            <div>
                <h5>Overall</h5>
                {{overall}}
            </div>
            <div>
                <h5>Price</h5>
                {{price}}
            </div>
            <a class="buy" href="{{link}}">Buy</a>
        </li>
        {{else}}
            <li>
                No matches found. <% if user_signed_in? && current_user.is_admin %><a href="/products/{{id}}/matches/new">Add one?</a><% end %>
            </li>
        {{/each}}
    </ul>
</script>

app/views/products/matrix.html.erb
<div class="container">
	<div class="page-header">
		<h1>Products</h1>
	</div>
	<% @products.each do |product| %>
		<div class="row product solid-white">
			<div class="one_sixth"><%= image_tag product.photo(:square) %></div>
			<div class="two_thirds">
				<h4><strong><%= product.brand.name %></strong> <%= product.name %></h4>
				<p><%= product.description %></p>
			</div>
			<div class="one_sixth last_column">
				<div class="text-center">
					<h4><%= product.area.name %></h4>
					<div class="category-name"><%= product.category.name %></div>
				</div>
				<div class="text-center">
					<%= link_to "#{product.matches.count} Matches", product_matches_path(product), :class => 'btn btn-primary' %><br />
					<%= link_to 'Edit', edit_product_path(product), :class => 'btn btn-warning' %>
					<%= link_to 'Delete', product_path(product), :method => :delete, :class => 'btn btn-danger', :data => { :confirm => "Are you sure you want to delete this product?" } %>
				</div>
			</div>
		</div>
	<% end %>
	<div class="row product text-center">
		<%= link_to "New product", new_product_path, :class => 'btn btn-success btn-large' %>
	</div>
</div>

app/views/products/new.html.erb
<div class="container">
	<div class="page-header">
		<h1>Add a new product</h1>
	</div>
	<%= render 'form' %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Link:</b>
  <%= @product.link %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Brand:</b>
  <%= @product.brand.name %>
</p>

<p>
  <b>Area:</b>
  <%= @product.area.name %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category.name %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>