config/routes.rb
Mtm::Application.routes.draw do
  devise_for :users

  resources :categories

  resources :areas

  resources :brands

  resources :products do
    resources :matches
  end

  root :to => 'pages#home'

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40105023-1', 'herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
		<div class="one_fourth">
			<h2>Navigate</h2>
			<% if user_signed_in? && current_user.is_bear %>
				<%= link_to "Brands", brands_path %><br />
				<%= link_to "Areas", areas_path %><br />
				<%= link_to "Categories", categories_path %>
			<% else %>
				<a href="#">Home</a><br>
				<a href="#">About</a><br>
				<a href="#">Contact</a>
			<% end %>
		</div>
		<div class="one_fourth">
			<h2>Shopping</h2>
			<a href="#">Register</a><br>
			<a href="#">Account</a><br>
			<a href="#">Shopping Bag</a>
		</div>
		<div class="one_fourth">
			<h2>Social</h2>
			<a href="#">Facebook</a><br>
			<a href="#">Twitter</a><br>
			<a href="#">Tumblr</a>
		</div>
		<div class="one_fourth">
			<h2>Info</h2>
			<a href="#">Terms</a><br>
			<a href="#">Privacy</a><br>
			<a href="#">Other</a>
		</div>
	</div>
	<span class="copyright">
		<br>
		<% if !user_signed_in? %>
			<%= link_to image_tag('footer_kiss.png'), new_user_session_path %>
		<% else %>
			<%= image_tag 'footer_kiss.png' %>
		<% end %>
		<br>
		All rights reserved. © 2012 Match that Makeup</span>
</div>

app/views/layouts/_nav.html.erb
<div class="navigation">
	<%= link_to image_tag('howitworks_3.png', :size => '100x100', :class => 'left'), root_path %>
	<div class="nav-inner">
		<% if user_signed_in? %>
			<%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => 'btn btn-small btn-inverse right' %>
			<% if current_user.is_admin? %>
				<%= link_to "Products", products_path, :class => 'btn btn-small btn-inverse right' %>
			<% end %>
		<% end %>
	</div>
	<% flash.each do |type, message| %>
    <div class="alert <%= flash_class type %>">
      <h1><%= message %></h1>
    </div>
    <div class="clearfix"></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Match that Makeup</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script type="text/javascript" src="//use.typekit.net/rph7kjs.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <link href='http://fonts.googleapis.com/css?family=Raleway:100,200' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/analytics' %>
</head>
<body>
	<%= render 'layouts/nav' %>

  <%= yield %>
  <%= render 'layouts/footer' %>
	<script>
      $(function() {
        window.addEventListener("load",function() {
          setTimeout(function(){
            window.scrollTo(0, 1);
          }, 0);
        });
      });
    </script>
</body>
</html>

app/views/layouts/clean.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Match that Makeup</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script type="text/javascript" src="//use.typekit.net/rph7kjs.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <link href='http://fonts.googleapis.com/css?family=Raleway:100,200' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/analytics' %>
</head>
<body>
  <% flash.each do |type, message| %>
    <div class="alert <%= flash_class type %>">
      <h1><%= message %></h1>
    </div>
    <div class="clearfix"></div>
  <% end %>
  <%= yield %>
	<script>
      $(function() {
        window.addEventListener("load",function() {
          setTimeout(function(){
            window.scrollTo(0, 1);
          }, 0);
        });
      });
    </script>
</body>
</html>